keybase/keybase-bot

README.md

When using the package, I didn't know that the callback was a required argument and neglected to include it when calling `bot.init()` in a REPL session. This change tries to clarify that requirement.

Update README.md with callback requirement

---

.vscode/launch.json
README.md
demos/check_for_unreads.js
demos/hello_world.js
demos/math_bot.js
lib/bot.js
lib/full-watcher.js
lib/gas-preserver.js
lib/tweakables.js

With the introduction of one-shot mode, there wasn't a way to log the bot out after `bot.init()` was run. I think the best solution to this problem is to add a `bot.deinit()` method that should be run at the end of every bot program.
Other changes:
- Added/changed documentation (both in readme and jsdoc) to reflect the `bot.deinit()` addition
- Added a VSCode debug task for math bot 🤖 
- Fixed some issues with math bot, but I think more rigorous testing is needed. I stop it from crashing, but I'm getting an issue where it's looking at all messages in a chat instead of just new ones. It seemed a little outside the scope of this PR, but would probably be something good to look at when we restructure the chat stuff as per #18 
- Changed the examples to use async/await, which I think fit the …

Add a `deinit` bot method

---

demos/hello_world.js
lib/bot.js
lib/keybase-exec.js

Closes #5. Some notes:
- I think it makes more sense for `keybaseExec` to take in its parameters via actual function parameters instead of a `Params` object. This was a pretty easy change since we're only using it in `init` right now.
- I was getting an issue with the bot expecting stdin if none was provided. My solution was to just always end the stream instead of only ending the stream if we write data in. I think better reflects the behavior we want.

Pass paperkey via stdin

---

demos/check_for_unreads.js
lib/chat/index.js

Since the demo filters unread conversations, we don't want just the unread messages from the service. It looks like the unread only option was only introduced when we updated the flow types #13.
I only realized this would be an issue when I ran this demo while having no unread messages – I got a type error for trying to run `filter` on `null`. Even with unread messages, though, the results aren't correct as `res.conversations.length` doesn't give the number of conversations, but just the ones with unread messages.
I also added a check in the rare case someone runs this on an account where there are no conversations (and `res` is thus `null`).

Don't just get unread conversations in `check_for_unreads` demo

---

lib/utils.js

This captures the STDERR from the child process (keybase service) and uses the result as the Error message for the library's return.
Closes #32

Pass Keybase Service STDERR Back to Error Message

---

lib/base/index.js
lib/chat/index.js
lib/store/actions.js
lib/store/index.js
lib/store/reducer.js
lib/store/types.js
lib/types.js
lib/utils.js

hi @nathunsmitty and @thebearjew - 
coupla things:
1. `keybaseHomeDir` -> `homeDir` , as requested.
2. I implemented a rmdir that cleans up all the levelDB and other crap that keybase makes. It works, although I wouldn't mind you taking a look at the function to give me feedback on ES6 code style escp. for async/await functions, which is all new to me. Here's the fn; I noticed that `util` coming with node 8+ comes with a promisify, so this all works without external deps. This kind of stuff sure is prettier in iced coffee script :-)
```javascript
export async function rmdirRecursive(dirName: string): Promise<void> {
const fsLstat = promisify(fs.lstat)
const fsUnlink = promisify(fs.unlink)
const fsRmdir = promisify(fs.rmdir)
const fsReaddir = promisify(fs.readdir)
try {
const dirStat = …
```

recursive cleanup + keybaseHomeDir rename

---

__tests__/alice-init.test.js
__tests__/count-to-10.test.js
__tests__/shutdown.test.js
__tests__/team-hello.test.js
__tests__/tests.config.example.js

This adds a new test for sending and reading messge(s) in a team. It's roughly the same as sending in non-team chats, with a slightly different team structure.
The test config file changed slightly, so to get the tests to pass you'll need to edit your local `tests.config.js` file that you make out of `tests.config.example.js`. In particular it now also wants to know about a team.
also edited the alice1 and bob1 DM testing so they can count to 10 together with a unique code, in case there are other concurrent tests.

test for team sends; cleanup other tests

---

.eslintrc
__tests__/count-to-10.test.js
__tests__/setup.js
__tests__/shutdown.test.js
__tests__/team-hello.test.js
jest.config.js

I think my computer may run a little slower than @malgorithms, since Jest always seems to give me timeout errors when I run our tests. This adds a config file and an upper timeout bound of 30 seconds, which I think should solve the problem for most computers.
Also fixed an import that I didn't catch in my last PR.

Global test timeout fix

---

demos/es7/math-bot-es7.js
demos/math-bot.js
lib/chat/index.js
lib/chat/types.js

Better typing and error handling of chat notifications we get through `chat api-listen`. This was originally inspired by #63, but as I dug into I realized that case was just due us not properly parsing errors in notifications.
I didn't want to hide notifications completely since I think there are cases where they could be useful, hence the optional new `onError` parameter. If no `onError` is passed, all errors that occur in any notification body or in an `onMessage` callback will be silently caught. If an `onError` is specified, these errors will be handled by `onError`. If `onError` itself throws an error, then the watch method that it was passed to will throw that error, since that's probably indicative of something wrong in your code, not Keybase chat, and it doesn't make sense to have …

Add `onError` handler for watch methods (Closes #63)

---

.yarnrc

So something like
```
yarn add lodash.snakecase
```
results in
```
"dependencies": {
"lodash.snakecase": "4.1.1"
},
```
instead of
```
"dependencies": {
"lodash.snakecase": "^4.1.1"
},
```
This based off our decision in #60 and #61.

Add yarn configuration for exact types 

---

README.md
__tests__/chat.test.js
__tests__/setup.js
lib/chat-client/index.js

@nathunsmitty, small changes here although lots diffs in chat.test.js because the bot `alice` is now `alice1` and `alice2`.
the key change here is that watching for new messages now by default includes your own message sent from other devices. I decided to resolve the issue (#65) in the simplest imaginable way: just let the user look at the data themselves if they want to filter these out. 
so, watching for new messages:
- includes messages from others
- includes messages from your other devices 
- does not include messages from the same device that's running the bot
also note I call your `formatAPIObjectOutput` on the watched messages, which we weren't doing.

watching for messages now includes ones own from other devices

---

.vscode/launch.json
README.md
__tests__/tests.config.example.js
__tests__/wallet.test.js
lib/chat-client/index.js
lib/client-base/index.js
lib/constants.js
lib/index.js
lib/utils/formatAPIObject.js
lib/utils/formatAPIObject.test.js
lib/wallet-client/index.js
lib/wallet-client/types.js
package.json
rollup.config.js
yarn.lock

Supported wallet methods:
- balances
- history
- details
- lookup
- send
- cancel
I didn't implement the inflation methods just yet because those seemed a little niche, and I wanted to get a base implementation done first.
Other notes:
- I added breakpoint debugging support for our jest tests in VS Code
- Some wallet tests require a user who hasn't yet set up a wallet; this required a new bot named charlie.
- The wallet api uses different casing than the chat api, so formatAPIObject now supports kebab-case

feat: Add wallet support

---

README.md
__tests__/init.test.js
__tests__/myInfo.test.js
__tests__/test-utils/startServiceManually.js
lib/client-base/index.js
lib/index.js
lib/service/index.js
lib/utils/keybaseStatus.js
lib/utils/options.js

`-enable-mode-lite-mode` supersedes `KEYBASE_DISABLE_TEAM_AUDITOR` and disables some other non essentials. depends on https://github.com/keybase/client/pull/15672 merging

bot lite mode

---

README.md
lib/chat-client/index.js

Some examples passed in params as a map instead of separately. This updates those and regens the docs

docs: update examples of using chat.send

---

lib/chat-client/types.js

Strangely here https://github.com/keybase/client/blob/b6aadbbd398c09010a6469de78f68b5db80cc9c6/protocol/json/chat1/local.json#L126 it's also written as `messageID`, but I receive `messageId`:
I guess `formatAPIObjectOutput` function changes that?
**upd**: Yep: `require('lodash.camelcase')('messageID') //=> 'messageId'`
Also it doesn't touch `messageIDs`: `require('lodash.camelcase')('messageIDs') //=> 'messageIDs'`

Fix EditContent in flow typings: 'messageID' -> 'messageId'

---

__tests__/chat.test.js

We'll test minimal count rather than `.last`. The bug on your accs was caused by the fact that unreadOnly  filtering is performed _after_ the pagination is done. Unfortunately pagination after filtering is hard to implement without changing the local thread viewing APIs, so this is as good as it gets.
fixes #125

pagination test fix

---

lib/chat-client/types.d.ts
src/chat-client/types.ts

I think this is a number. The `id` field of `MessageSummary` is `number`: https://github.com/keybase/keybase-bot/blob/71da5e4daacffef5ee09ab080bce1e332d01ee9a/src/chat-client/types.ts#L213
And the `m` field from `api-listen` is `number` instead of `string` too:
```
{"type":"chat","source":"remote","msg":{"id":274,"conversation_id":"0000fc8540f720b1109de1283292545e7fbcdcd813e6126f524193a87abca2c1","channel":{"name":"songgao,songgao_test","public":false,"members_type":"impteamupgrade","topic_type":"chat"},"sender":{"uid":"08abe80bd2da8984534b2d8f7b12c700","username":"songgao","device_id":"189239cee2a9b425ad7016454ae3ad18","device_name":"mbp-kb-20190417"},"sent_at":1562556327,"sent_at_ms":1562556327612,"content":{"type":"reaction","reaction":{"m":271,"b":":+1:"}},"prev":null,"unread":false,"c …
```

fix m ReactionContent typing

---

.gitattributes

This should make the GitHub diffs easier to read by hiding the generated files of `lib/` by default. We do the same thing in the client repo for the generated RPC types!

Mark lib/ directory as linguist-generated

---

package.json

Adds a `types` entry to the package.json so that typescript apps that use this package can take advantage of our types. See https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package for details.
I was really confused about why my bot import was `any` and this fixes that haha

Add types field for use by typescript apps

---

demos/es7/advertised-echo.js

Looks like just the advertisement syntax was broken. Otherwise the demo works fine.

Correct bot advertisements to demo restricted bots

---

README.md

Hi,
Currently, the example of Dockerfile is error-prone.
When you try to run it with typescript, which generates `/dist` it will fail due to Permission access error.
After some investigation, I've figured out that `keybaseio/client:nightly-node-slim` leave the image with `keybase` user. Command `WORKDIR /app` creates the `/app` directory at root level access, which prevents from creating there `/dist` directory.
My proposal is to set `WORKDIR` to `/home/keybase` (where the user has write access)  by default.
Additionally 
```
COPY package*.json ./
RUN npm install # or use yarn
COPY . .
```
for free performance improvement.

improve docker example

---

lib/kvstore-client/index.d.ts
lib/kvstore-client/index.js
src/kvstore-client/index.ts

Correct destructured fulfillment value (c.f. keybase1.KVGetResult)

docs: update @example for bot.kvstore.get
